export interface Cnae {
  codigo: string
  descricao: string
  secao: string
}

export const CNAES: Cnae[] = [
  // A - AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQUICULTURA
  { secao: "Agricultura e Pecuária", codigo: "0111301", descricao: "Cultivo de arroz" },
  { secao: "Agricultura e Pecuária", codigo: "0111302", descricao: "Cultivo de milho" },
  { secao: "Agricultura e Pecuária", codigo: "0111303", descricao: "Cultivo de trigo" },
  { secao: "Agricultura e Pecuária", codigo: "0115600", descricao: "Cultivo de soja" },
  { secao: "Agricultura e Pecuária", codigo: "0119901", descricao: "Cultivo de flores e plantas ornamentais" },
  { secao: "Agricultura e Pecuária", codigo: "0121101", descricao: "Horticultura" },
  { secao: "Agricultura e Pecuária", codigo: "0131800", descricao: "Cultivo de laranja" },
  { secao: "Agricultura e Pecuária", codigo: "0133401", descricao: "Cultivo de café" },
  { secao: "Agricultura e Pecuária", codigo: "0134200", descricao: "Cultivo de cana-de-açúcar" },
  { secao: "Agricultura e Pecuária", codigo: "0141501", descricao: "Criação de bovinos para corte" },
  { secao: "Agricultura e Pecuária", codigo: "0141502", descricao: "Criação de bovinos para leite" },
  { secao: "Agricultura e Pecuária", codigo: "0155501", descricao: "Criação de frangos para corte" },
  { secao: "Agricultura e Pecuária", codigo: "0159801", descricao: "Apicultura" },
  { secao: "Agricultura e Pecuária", codigo: "0162803", descricao: "Serviço de pulverização e controle de pragas agrícolas" },

  // B - INDÚSTRIAS EXTRATIVAS
  { secao: "Indústrias Extrativas", codigo: "0500301", descricao: "Extração de carvão mineral" },
  { secao: "Indústrias Extrativas", codigo: "0600001", descricao: "Extração de petróleo e gás natural" },
  { secao: "Indústrias Extrativas", codigo: "0810001", descricao: "Extração de ardósia e seus trabalhos" },
  { secao: "Indústrias Extrativas", codigo: "0891600", descricao: "Extração de minerais para fabricação de adubos" },

  // C - INDÚSTRIAS DE TRANSFORMAÇÃO
  { secao: "Indústria Alimentícia", codigo: "1011201", descricao: "Frigorífico - abate de bovinos" },
  { secao: "Indústria Alimentícia", codigo: "1011202", descricao: "Frigorífico - abate de equinos" },
  { secao: "Indústria Alimentícia", codigo: "1012101", descricao: "Abate de aves" },
  { secao: "Indústria Alimentícia", codigo: "1013901", descricao: "Fabricação de produtos de carne" },
  { secao: "Indústria Alimentícia", codigo: "1020101", descricao: "Preservação de peixes, crustáceos e moluscos" },
  { secao: "Indústria Alimentícia", codigo: "1031700", descricao: "Fabricação de conservas de frutas" },
  { secao: "Indústria Alimentícia", codigo: "1041400", descricao: "Fabricação de óleos vegetais em bruto" },
  { secao: "Indústria Alimentícia", codigo: "1051100", descricao: "Preparação do leite" },
  { secao: "Indústria Alimentícia", codigo: "1052000", descricao: "Fabricação de laticínios" },
  { secao: "Indústria Alimentícia", codigo: "1061901", descricao: "Beneficiamento de arroz" },
  { secao: "Indústria Alimentícia", codigo: "1062700", descricao: "Moagem de trigo e fabricação de derivados" },
  { secao: "Indústria Alimentícia", codigo: "1064300", descricao: "Fabricação de farinha de milho e derivados" },
  { secao: "Indústria Alimentícia", codigo: "1071600", descricao: "Fabricação de açúcar" },
  { secao: "Indústria Alimentícia", codigo: "1081301", descricao: "Beneficiamento de café" },
  { secao: "Indústria Alimentícia", codigo: "1082100", descricao: "Torrefação e moagem de café" },
  { secao: "Indústria Alimentícia", codigo: "1089900", descricao: "Fabricação de outros produtos alimentares" },
  { secao: "Indústria Alimentícia", codigo: "1091100", descricao: "Fabricação de produtos de panificação industrial" },
  { secao: "Indústria Alimentícia", codigo: "1092900", descricao: "Fabricação de biscoitos e bolachas" },
  { secao: "Indústria Alimentícia", codigo: "1113501", descricao: "Fabricação de cervejas e chopes" },
  { secao: "Indústria Alimentícia", codigo: "1122401", descricao: "Fabricação de refrigerantes" },
  { secao: "Indústria Têxtil", codigo: "1311100", descricao: "Preparação e fiação de fibras de algodão" },
  { secao: "Indústria Têxtil", codigo: "1321900", descricao: "Tecelagem de fios de algodão" },
  { secao: "Indústria Têxtil", codigo: "1340599", descricao: "Outros serviços de acabamento em fios e tecidos" },
  { secao: "Vestuário", codigo: "1411801", descricao: "Confecção de roupas íntimas" },
  { secao: "Vestuário", codigo: "1412603", descricao: "Facção de roupas íntimas" },
  { secao: "Vestuário", codigo: "1421500", descricao: "Fabricação de meias" },
  { secao: "Vestuário", codigo: "1422300", descricao: "Fabricação de artigos do vestuário" },
  { secao: "Couro e Calçados", codigo: "1510600", descricao: "Curtimento e outras preparações de couro" },
  { secao: "Couro e Calçados", codigo: "1531901", descricao: "Fabricação de calçados de couro" },
  { secao: "Madeira", codigo: "1610201", descricao: "Serrarias com desdobramento de madeira" },
  { secao: "Madeira", codigo: "1622601", descricao: "Fabricação de casas de madeira pré-fabricadas" },
  { secao: "Papel e Celulose", codigo: "1710900", descricao: "Fabricação de celulose e outras pastas" },
  { secao: "Papel e Celulose", codigo: "1721400", descricao: "Fabricação de papel" },
  { secao: "Gráfica", codigo: "1811301", descricao: "Impressão de jornais" },
  { secao: "Gráfica", codigo: "1812100", descricao: "Impressão de material de segurança" },
  { secao: "Gráfica", codigo: "1813001", descricao: "Impressão de material para uso publicitário" },
  { secao: "Gráfica", codigo: "1821100", descricao: "Serviços de pré-impressão" },
  { secao: "Gráfica", codigo: "1822901", descricao: "Serviços de encadernação e plastificação" },
  { secao: "Química", codigo: "2011800", descricao: "Fabricação de cloro e álcalis" },
  { secao: "Química", codigo: "2012600", descricao: "Fabricação de intermediários para fertilizantes" },
  { secao: "Química", codigo: "2013400", descricao: "Fabricação de adubos e fertilizantes" },
  { secao: "Química", codigo: "2021500", descricao: "Fabricação de produtos petroquímicos básicos" },
  { secao: "Química", codigo: "2031200", descricao: "Fabricação de resinas termoplásticas" },
  { secao: "Química", codigo: "2061400", descricao: "Fabricação de sabões e detergentes sintéticos" },
  { secao: "Química", codigo: "2062200", descricao: "Fabricação de produtos de limpeza e polimento" },
  { secao: "Química", codigo: "2063100", descricao: "Fabricação de cosméticos, produtos de perfumaria e higiene pessoal" },
  { secao: "Farmacêutica", codigo: "2121101", descricao: "Fabricação de medicamentos alopáticos para uso humano" },
  { secao: "Farmacêutica", codigo: "2121102", descricao: "Fabricação de medicamentos homeopáticos para uso humano" },
  { secao: "Farmacêutica", codigo: "2122000", descricao: "Fabricação de medicamentos para uso veterinário" },
  { secao: "Borracha e Plástico", codigo: "2211100", descricao: "Fabricação de pneumáticos e câmaras-de-ar" },
  { secao: "Borracha e Plástico", codigo: "2221800", descricao: "Fabricação de laminados planos e tubulares de plástico" },
  { secao: "Borracha e Plástico", codigo: "2229301", descricao: "Fabricação de artefatos de material plástico para uso pessoal" },
  { secao: "Minerais Não Metálicos", codigo: "2311700", descricao: "Fabricação de vidro plano e de segurança" },
  { secao: "Minerais Não Metálicos", codigo: "2341900", descricao: "Fabricação de produtos cerâmicos refratários" },
  { secao: "Minerais Não Metálicos", codigo: "2342701", descricao: "Fabricação de azulejos e pisos" },
  { secao: "Minerais Não Metálicos", codigo: "2391501", descricao: "Britamento de granito" },
  { secao: "Minerais Não Metálicos", codigo: "2394800", descricao: "Fabricação de cal e gesso" },
  { secao: "Metalurgia", codigo: "2411300", descricao: "Produção de ferro-gusa" },
  { secao: "Metalurgia", codigo: "2422901", descricao: "Produção de alumínio" },
  { secao: "Metalurgia", codigo: "2439300", descricao: "Metalurgia dos metais preciosos" },
  { secao: "Metal", codigo: "2512800", descricao: "Fabricação de esquadrias de metal" },
  { secao: "Metal", codigo: "2521700", descricao: "Fabricação de tanques e reservatórios metálicos" },
  { secao: "Metal", codigo: "2531401", descricao: "Produção de forjados de aço" },
  { secao: "Metal", codigo: "2541100", descricao: "Fabricação de artigos de cutelaria" },
  { secao: "Metal", codigo: "2542000", descricao: "Fabricação de artigos de serralheria" },
  { secao: "Metal", codigo: "2543800", descricao: "Fabricação de ferramentas" },
  { secao: "Metal", codigo: "2591800", descricao: "Fabricação de embalagens metálicas" },
  { secao: "Eletrônica", codigo: "2610800", descricao: "Fabricação de componentes eletrônicos" },
  { secao: "Eletrônica", codigo: "2621300", descricao: "Fabricação de equipamentos de informática" },
  { secao: "Eletrônica", codigo: "2622100", descricao: "Fabricação de periféricos para equipamentos de informática" },
  { secao: "Eletrônica", codigo: "2631100", descricao: "Fabricação de equipamentos transmissores de comunicação" },
  { secao: "Eletrônica", codigo: "2640000", descricao: "Fabricação de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo" },
  { secao: "Eletrônica", codigo: "2670101", descricao: "Fabricação de equipamentos e instrumentos ópticos" },
  { secao: "Máquinas e Equipamentos", codigo: "2811900", descricao: "Fabricação de motores e turbinas" },
  { secao: "Máquinas e Equipamentos", codigo: "2821600", descricao: "Fabricação de fornos industriais" },
  { secao: "Máquinas e Equipamentos", codigo: "2833000", descricao: "Fabricação de máquinas e equipamentos para agricultura" },
  { secao: "Máquinas e Equipamentos", codigo: "2853400", descricao: "Fabricação de máquinas e equipamentos para terraplenagem" },
  { secao: "Máquinas e Equipamentos", codigo: "2862300", descricao: "Fabricação de máquinas e ferramentas" },
  { secao: "Veículos", codigo: "2910701", descricao: "Fabricação de automóveis, camionetas e utilitários" },
  { secao: "Veículos", codigo: "2920401", descricao: "Fabricação de caminhões e ônibus" },
  { secao: "Veículos", codigo: "2930101", descricao: "Fabricação de cabines, carrocerias e reboques" },
  { secao: "Veículos", codigo: "2945000", descricao: "Fabricação de peças e acessórios para veículos automotores" },
  { secao: "Móveis", codigo: "3101200", descricao: "Fabricação de móveis com predominância de madeira" },
  { secao: "Móveis", codigo: "3102100", descricao: "Fabricação de móveis com predominância de metal" },
  { secao: "Móveis", codigo: "3103900", descricao: "Fabricação de móveis de outros materiais" },

  // F - CONSTRUÇÃO
  { secao: "Construção", codigo: "4110700", descricao: "Incorporação de empreendimentos imobiliários" },
  { secao: "Construção", codigo: "4120400", descricao: "Construção de edifícios" },
  { secao: "Construção", codigo: "4211101", descricao: "Construção de rodovias e ferrovias" },
  { secao: "Construção", codigo: "4211102", descricao: "Pintura para sinalização em pistas rodoviárias e aeroportos" },
  { secao: "Construção", codigo: "4213800", descricao: "Obras de urbanização e paisagismo" },
  { secao: "Construção", codigo: "4221901", descricao: "Construção de barragens e represas" },
  { secao: "Construção", codigo: "4222701", descricao: "Construção de redes de abastecimento de água" },
  { secao: "Construção", codigo: "4223500", descricao: "Construção de redes de transportes por dutos" },
  { secao: "Construção", codigo: "4291000", descricao: "Obras portuárias, marítimas e fluviais" },
  { secao: "Construção", codigo: "4292801", descricao: "Montagem de estruturas metálicas" },
  { secao: "Construção", codigo: "4311801", descricao: "Demolição de edifícios e outras estruturas" },
  { secao: "Construção", codigo: "4312600", descricao: "Perfurações e sondagens" },
  { secao: "Construção", codigo: "4313400", descricao: "Obras de terraplenagem" },
  { secao: "Construção", codigo: "4321500", descricao: "Instalação e manutenção elétrica" },
  { secao: "Construção", codigo: "4322301", descricao: "Instalações hidráulicas, sanitárias e de gás" },
  { secao: "Construção", codigo: "4322302", descricao: "Instalação e manutenção de sistemas centrais de ar condicionado" },
  { secao: "Construção", codigo: "4329101", descricao: "Instalação de painéis publicitários" },
  { secao: "Construção", codigo: "4329103", descricao: "Instalação, manutenção e reparação de elevadores" },
  { secao: "Construção", codigo: "4330401", descricao: "Impermeabilização em obras de engenharia civil" },
  { secao: "Construção", codigo: "4330402", descricao: "Instalação de portas, janelas, tetos, divisórias e armários" },
  { secao: "Construção", codigo: "4330403", descricao: "Obras de acabamento em gesso e estuque" },
  { secao: "Construção", codigo: "4330404", descricao: "Serviços de pintura de edifícios" },
  { secao: "Construção", codigo: "4330405", descricao: "Aplicação de revestimentos e de resinas em interiores e exteriores" },
  { secao: "Construção", codigo: "4391600", descricao: "Obras de fundações" },
  { secao: "Construção", codigo: "4399101", descricao: "Administração de obras" },
  { secao: "Construção", codigo: "4399103", descricao: "Obras de alvenaria" },
  { secao: "Construção", codigo: "4399104", descricao: "Serviços de operação e fornecimento de equipamentos para transporte" },
  { secao: "Construção", codigo: "4399105", descricao: "Perfuração e construção de poços de água" },

  // G - COMÉRCIO
  { secao: "Comércio de Veículos", codigo: "4511101", descricao: "Comércio de automóveis, camionetas e utilitários novos" },
  { secao: "Comércio de Veículos", codigo: "4511102", descricao: "Comércio de automóveis, camionetas e utilitários usados" },
  { secao: "Comércio de Veículos", codigo: "4512901", descricao: "Representantes comerciais de veículos automotores" },
  { secao: "Comércio de Veículos", codigo: "4520001", descricao: "Serviços de manutenção e reparação de automóveis e utilitários" },
  { secao: "Comércio de Veículos", codigo: "4530701", descricao: "Comércio de peças e acessórios para veículos automotores" },
  { secao: "Comércio de Veículos", codigo: "4541206", descricao: "Comércio varejista de motocicletas novas" },
  { secao: "Comércio de Veículos", codigo: "4542102", descricao: "Reparação e manutenção de motocicletas e motonetas" },
  { secao: "Comércio Atacadista", codigo: "4621400", descricao: "Comércio atacadista de café em grão" },
  { secao: "Comércio Atacadista", codigo: "4622200", descricao: "Comércio atacadista de soja" },
  { secao: "Comércio Atacadista", codigo: "4623109", descricao: "Comércio atacadista de alimentos para animais" },
  { secao: "Comércio Atacadista", codigo: "4631100", descricao: "Comércio atacadista de leite e laticínios" },
  { secao: "Comércio Atacadista", codigo: "4632001", descricao: "Comércio atacadista de cereais e leguminosas" },
  { secao: "Comércio Atacadista", codigo: "4641901", descricao: "Comércio atacadista de tecidos" },
  { secao: "Comércio Atacadista", codigo: "4644301", descricao: "Comércio atacadista de medicamentos e drogas de uso humano" },
  { secao: "Comércio Atacadista", codigo: "4645101", descricao: "Comércio atacadista de instrumentos e materiais para uso médico" },
  { secao: "Comércio Atacadista", codigo: "4646001", descricao: "Comércio atacadista de cosméticos e produtos de perfumaria" },
  { secao: "Comércio Atacadista", codigo: "4661300", descricao: "Comércio atacadista de máquinas, aparelhos e equipamentos para uso agropecuário" },
  { secao: "Comércio Atacadista", codigo: "4663000", descricao: "Comércio atacadista de máquinas e equipamentos para uso industrial" },
  { secao: "Comércio Atacadista", codigo: "4671100", descricao: "Comércio atacadista de madeira e produtos derivados" },
  { secao: "Comércio Atacadista", codigo: "4672900", descricao: "Comércio atacadista de ferragens e ferramentas" },
  { secao: "Comércio Atacadista", codigo: "4674500", descricao: "Comércio atacadista de cimento" },
  { secao: "Comércio Atacadista", codigo: "4681801", descricao: "Comércio atacadista de álcool carburante, biodiesel, gasolina e demais derivados de petróleo" },
  { secao: "Comércio Atacadista", codigo: "4686901", descricao: "Comércio atacadista de papel e papelão em bruto" },
  { secao: "Comércio Atacadista", codigo: "4687701", descricao: "Comércio atacadista de resíduos de papel e papelão" },
  { secao: "Comércio Varejista", codigo: "4711301", descricao: "Comércio varejista de mercadorias em geral - hipermercados" },
  { secao: "Comércio Varejista", codigo: "4711302", descricao: "Comércio varejista de mercadorias em geral - supermercados" },
  { secao: "Comércio Varejista", codigo: "4712100", descricao: "Comércio varejista de mercadorias em geral - minimercados, mercearias e armazéns" },
  { secao: "Comércio Varejista", codigo: "4721102", descricao: "Padaria e confeitaria com predominância de revenda" },
  { secao: "Comércio Varejista", codigo: "4721103", descricao: "Comércio varejista de laticínios e frios" },
  { secao: "Comércio Varejista", codigo: "4722901", descricao: "Comércio varejista de carnes - açougues" },
  { secao: "Comércio Varejista", codigo: "4731800", descricao: "Comércio varejista de combustíveis para veículos automotores" },
  { secao: "Comércio Varejista", codigo: "4741500", descricao: "Comércio varejista de tintas e materiais para pintura" },
  { secao: "Comércio Varejista", codigo: "4742300", descricao: "Comércio varejista de material elétrico" },
  { secao: "Comércio Varejista", codigo: "4744001", descricao: "Comércio varejista de ferragens e ferramentas" },
  { secao: "Comércio Varejista", codigo: "4744002", descricao: "Comércio varejista de madeira e artefatos" },
  { secao: "Comércio Varejista", codigo: "4744004", descricao: "Comércio varejista de cal, areia, pedra britada, tijolos e telhas" },
  { secao: "Comércio Varejista", codigo: "4751201", descricao: "Comércio varejista de equipamentos e suprimentos de informática" },
  { secao: "Comércio Varejista", codigo: "4751202", descricao: "Recarga de cartuchos para equipamentos de informática" },
  { secao: "Comércio Varejista", codigo: "4752100", descricao: "Comércio varejista especializado de equipamentos de telefonia e comunicação" },
  { secao: "Comércio Varejista", codigo: "4753900", descricao: "Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo" },
  { secao: "Comércio Varejista", codigo: "4754701", descricao: "Comércio varejista de móveis" },
  { secao: "Comércio Varejista", codigo: "4761003", descricao: "Comércio varejista de brinquedos e artigos recreativos" },
  { secao: "Comércio Varejista", codigo: "4762800", descricao: "Comércio varejista de discos, CDs, DVDs e fitas" },
  { secao: "Comércio Varejista", codigo: "4771701", descricao: "Comércio varejista de produtos farmacêuticos sem manipulação" },
  { secao: "Comércio Varejista", codigo: "4771702", descricao: "Comércio varejista de produtos farmacêuticos com manipulação" },
  { secao: "Comércio Varejista", codigo: "4772500", descricao: "Comércio varejista de cosméticos, produtos de perfumaria e higiene pessoal" },
  { secao: "Comércio Varejista", codigo: "4774100", descricao: "Comércio varejista de artigos de óptica" },
  { secao: "Comércio Varejista", codigo: "4781400", descricao: "Comércio varejista de artigos do vestuário e acessórios" },
  { secao: "Comércio Varejista", codigo: "4782201", descricao: "Comércio varejista de calçados" },
  { secao: "Comércio Varejista", codigo: "4783101", descricao: "Comércio varejista de artigos de joalheria" },
  { secao: "Comércio Varejista", codigo: "4784900", descricao: "Comércio varejista de gás liqüefeito de petróleo (GLP)" },
  { secao: "Comércio Varejista", codigo: "4789001", descricao: "Comércio varejista de suvenires, bijuterias e artesanatos" },
  { secao: "Comércio Varejista", codigo: "4789004", descricao: "Comércio varejista de animais vivos e de artigos e alimentos para animais de estimação" },

  // H - TRANSPORTE
  { secao: "Transporte", codigo: "4911600", descricao: "Transporte ferroviário de carga" },
  { secao: "Transporte", codigo: "4921301", descricao: "Transporte rodoviário coletivo de passageiros - municipal" },
  { secao: "Transporte", codigo: "4922101", descricao: "Transporte rodoviário coletivo de passageiros - intermunicipal" },
  { secao: "Transporte", codigo: "4923001", descricao: "Serviço de táxi" },
  { secao: "Transporte", codigo: "4924800", descricao: "Transporte escolar" },
  { secao: "Transporte", codigo: "4929901", descricao: "Transporte rodoviário coletivo de passageiros - fretamento" },
  { secao: "Transporte", codigo: "4930201", descricao: "Transporte rodoviário de carga, exceto produtos perigosos e mudanças" },
  { secao: "Transporte", codigo: "4930202", descricao: "Transporte rodoviário de produtos perigosos" },
  { secao: "Transporte", codigo: "4930203", descricao: "Transporte rodoviário de mudanças" },
  { secao: "Transporte", codigo: "4940000", descricao: "Transporte dutoviário" },
  { secao: "Transporte", codigo: "4950700", descricao: "Trens turísticos, teleféricos e similares" },
  { secao: "Transporte", codigo: "5011401", descricao: "Transporte marítimo de cabotagem - carga" },
  { secao: "Transporte", codigo: "5091201", descricao: "Transporte por navegação de travessia" },
  { secao: "Transporte", codigo: "5111100", descricao: "Transporte aéreo de passageiros regular" },
  { secao: "Transporte", codigo: "5112901", descricao: "Serviço de táxi aéreo e locação de aeronaves com tripulação" },
  { secao: "Transporte", codigo: "5120000", descricao: "Transporte aéreo de carga" },
  { secao: "Transporte", codigo: "5212500", descricao: "Carga e descarga" },
  { secao: "Transporte", codigo: "5229001", descricao: "Serviços de apoio ao transporte por táxi" },
  { secao: "Transporte", codigo: "5229002", descricao: "Serviços de reboque de veículos" },
  { secao: "Logística", codigo: "5231101", descricao: "Administração da infra-estrutura portuária" },
  { secao: "Logística", codigo: "5310501", descricao: "Atividades do Correio Nacional" },
  { secao: "Logística", codigo: "5320201", descricao: "Serviços de malote não realizados pelo Correio Nacional" },
  { secao: "Logística", codigo: "5320202", descricao: "Serviços de entrega rápida" },

  // I - ALOJAMENTO E ALIMENTAÇÃO
  { secao: "Alojamento e Alimentação", codigo: "5510801", descricao: "Hotéis" },
  { secao: "Alojamento e Alimentação", codigo: "5510802", descricao: "Apart-hotéis" },
  { secao: "Alojamento e Alimentação", codigo: "5510803", descricao: "Motéis" },
  { secao: "Alojamento e Alimentação", codigo: "5590601", descricao: "Albergues, exceto assistenciais" },
  { secao: "Alojamento e Alimentação", codigo: "5590602", descricao: "Campings" },
  { secao: "Alojamento e Alimentação", codigo: "5611201", descricao: "Restaurantes e similares" },
  { secao: "Alojamento e Alimentação", codigo: "5611203", descricao: "Lanchonetes, casas de chá, de suco e similares" },
  { secao: "Alojamento e Alimentação", codigo: "5611204", descricao: "Bares e outros estabelecimentos especializados em servir bebidas" },
  { secao: "Alojamento e Alimentação", codigo: "5612100", descricao: "Serviços ambulantes de alimentação" },
  { secao: "Alojamento e Alimentação", codigo: "5620101", descricao: "Fornecimento de alimentos preparados para empresas" },
  { secao: "Alojamento e Alimentação", codigo: "5620102", descricao: "Serviços de alimentação para eventos e recepções - bufê" },

  // J - INFORMAÇÃO E COMUNICAÇÃO
  { secao: "Tecnologia da Informação", codigo: "5811500", descricao: "Edição de livros" },
  { secao: "Tecnologia da Informação", codigo: "5812301", descricao: "Edição de jornais diários" },
  { secao: "Tecnologia da Informação", codigo: "5813100", descricao: "Edição de revistas" },
  { secao: "Tecnologia da Informação", codigo: "5821200", descricao: "Edição integrada à impressão de livros" },
  { secao: "Tecnologia da Informação", codigo: "5911101", descricao: "Estúdios cinematográficos" },
  { secao: "Tecnologia da Informação", codigo: "5912001", descricao: "Serviços de dublagem" },
  { secao: "Tecnologia da Informação", codigo: "5913800", descricao: "Distribuição cinematográfica, de vídeo e de programas de televisão" },
  { secao: "Tecnologia da Informação", codigo: "5920100", descricao: "Atividades de gravação de som e de edição de música" },
  { secao: "Tecnologia da Informação", codigo: "6010100", descricao: "Rádio" },
  { secao: "Tecnologia da Informação", codigo: "6021700", descricao: "Televisão aberta" },
  { secao: "Tecnologia da Informação", codigo: "6110801", descricao: "Serviços de telefonia fixa comutada - STFC" },
  { secao: "Tecnologia da Informação", codigo: "6120501", descricao: "Telefonia móvel celular" },
  { secao: "Tecnologia da Informação", codigo: "6141800", descricao: "Operadoras de televisão por assinatura por cabo" },
  { secao: "Tecnologia da Informação", codigo: "6190601", descricao: "Provedores de acesso às redes de comunicações" },
  { secao: "Tecnologia da Informação", codigo: "6190602", descricao: "Provedores de voz sobre protocolo Internet - VoIP" },
  { secao: "Tecnologia da Informação", codigo: "6201501", descricao: "Desenvolvimento de programas de computador sob encomenda" },
  { secao: "Tecnologia da Informação", codigo: "6201502", descricao: "Web design" },
  { secao: "Tecnologia da Informação", codigo: "6202300", descricao: "Desenvolvimento e licenciamento de programas de computador customizáveis" },
  { secao: "Tecnologia da Informação", codigo: "6203100", descricao: "Desenvolvimento e licenciamento de programas de computador não customizáveis" },
  { secao: "Tecnologia da Informação", codigo: "6204000", descricao: "Consultoria em tecnologia da informação" },
  { secao: "Tecnologia da Informação", codigo: "6209100", descricao: "Suporte técnico, manutenção e outros serviços em tecnologia da informação" },
  { secao: "Tecnologia da Informação", codigo: "6311900", descricao: "Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na Internet" },
  { secao: "Tecnologia da Informação", codigo: "6319400", descricao: "Portais, provedores de conteúdo e outros serviços de informação na Internet" },
  { secao: "Tecnologia da Informação", codigo: "6391700", descricao: "Agências de notícias" },
  { secao: "Tecnologia da Informação", codigo: "6399200", descricao: "Outras atividades de prestação de serviços de informação" },

  // K - FINANCEIRO
  { secao: "Financeiro", codigo: "6411700", descricao: "Banco Central" },
  { secao: "Financeiro", codigo: "6422100", descricao: "Bancos múltiplos, com carteira comercial" },
  { secao: "Financeiro", codigo: "6423900", descricao: "Caixas econômicas" },
  { secao: "Financeiro", codigo: "6424701", descricao: "Bancos cooperativos" },
  { secao: "Financeiro", codigo: "6431000", descricao: "Bancos múltiplos, sem carteira comercial" },
  { secao: "Financeiro", codigo: "6432800", descricao: "Bancos de investimento" },
  { secao: "Financeiro", codigo: "6450600", descricao: "Sociedades de capitalização" },
  { secao: "Financeiro", codigo: "6461100", descricao: "Holdings de instituições financeiras" },
  { secao: "Financeiro", codigo: "6491300", descricao: "Sociedades de fomento mercantil - factoring" },
  { secao: "Financeiro", codigo: "6499901", descricao: "Clubes de investimento" },
  { secao: "Financeiro", codigo: "6511101", descricao: "Seguros de vida" },
  { secao: "Financeiro", codigo: "6512000", descricao: "Seguros não vida" },
  { secao: "Financeiro", codigo: "6521200", descricao: "Seguros saúde" },
  { secao: "Financeiro", codigo: "6611801", descricao: "Bolsa de valores" },
  { secao: "Financeiro", codigo: "6612601", descricao: "Corretoras de títulos e valores mobiliários" },
  { secao: "Financeiro", codigo: "6613400", descricao: "Administradoras de cartões de crédito" },
  { secao: "Financeiro", codigo: "6621501", descricao: "Peritos e avaliadores de seguros" },
  { secao: "Financeiro", codigo: "6631300", descricao: "Fundos de investimento" },

  // L - IMOBILIÁRIO
  { secao: "Imobiliário", codigo: "6810201", descricao: "Compra e venda de imóveis próprios" },
  { secao: "Imobiliário", codigo: "6810202", descricao: "Aluguel de imóveis próprios" },
  { secao: "Imobiliário", codigo: "6821801", descricao: "Corretagem na compra e venda e avaliação de imóveis" },
  { secao: "Imobiliário", codigo: "6821802", descricao: "Corretagem no aluguel de imóveis" },
  { secao: "Imobiliário", codigo: "6822600", descricao: "Gestão e administração da propriedade imobiliária" },

  // M - SERVIÇOS PROFISSIONAIS
  { secao: "Serviços Profissionais", codigo: "6910600", descricao: "Atividades jurídicas" },
  { secao: "Serviços Profissionais", codigo: "6920601", descricao: "Atividades de contabilidade" },
  { secao: "Serviços Profissionais", codigo: "6920602", descricao: "Atividades de consultoria e auditoria contábil e tributária" },
  { secao: "Serviços Profissionais", codigo: "7020400", descricao: "Atividades de consultoria em gestão empresarial" },
  { secao: "Serviços Profissionais", codigo: "7111100", descricao: "Serviços de arquitetura" },
  { secao: "Serviços Profissionais", codigo: "7112000", descricao: "Serviços de engenharia" },
  { secao: "Serviços Profissionais", codigo: "7119701", descricao: "Serviços de cartografia, topografia e geodésia" },
  { secao: "Serviços Profissionais", codigo: "7119703", descricao: "Serviços de desenho técnico relacionados à arquitetura e engenharia" },
  { secao: "Serviços Profissionais", codigo: "7119799", descricao: "Atividades técnicas relacionadas à engenharia e arquitetura" },
  { secao: "Serviços Profissionais", codigo: "7120100", descricao: "Testes e análises técnicas" },
  { secao: "Serviços Profissionais", codigo: "7210000", descricao: "Pesquisa e desenvolvimento experimental em ciências físicas e naturais" },
  { secao: "Serviços Profissionais", codigo: "7311400", descricao: "Agências de publicidade" },
  { secao: "Serviços Profissionais", codigo: "7312200", descricao: "Agenciamento de espaços para publicidade" },
  { secao: "Serviços Profissionais", codigo: "7319001", descricao: "Criação de estandes para feiras e exposições" },
  { secao: "Serviços Profissionais", codigo: "7319002", descricao: "Promoção de vendas" },
  { secao: "Serviços Profissionais", codigo: "7319003", descricao: "Marketing direto" },
  { secao: "Serviços Profissionais", codigo: "7319004", descricao: "Consultoria em publicidade" },
  { secao: "Serviços Profissionais", codigo: "7320300", descricao: "Pesquisas de mercado e de opinião pública" },
  { secao: "Serviços Profissionais", codigo: "7410202", descricao: "Design de interiores" },
  { secao: "Serviços Profissionais", codigo: "7410203", descricao: "Design de produto" },
  { secao: "Serviços Profissionais", codigo: "7420001", descricao: "Atividades de produção de fotografias" },
  { secao: "Serviços Profissionais", codigo: "7420004", descricao: "Filmagem de festas e eventos" },
  { secao: "Serviços Profissionais", codigo: "7490101", descricao: "Serviços de tradução, interpretação e similares" },
  { secao: "Serviços Profissionais", codigo: "7490104", descricao: "Atividades de intermediação e agenciamento de serviços e negócios em geral" },
  { secao: "Serviços Profissionais", codigo: "7490105", descricao: "Agenciamento de profissionais para atividades esportivas, culturais e artísticas" },
  { secao: "Serviços Profissionais", codigo: "7500100", descricao: "Atividades veterinárias" },

  // N - ADMINISTRATIVOS
  { secao: "Serviços Administrativos", codigo: "7711000", descricao: "Locação de automóveis sem condutor" },
  { secao: "Serviços Administrativos", codigo: "7719501", descricao: "Locação de embarcações sem tripulação" },
  { secao: "Serviços Administrativos", codigo: "7719502", descricao: "Locação de aeronaves sem tripulação" },
  { secao: "Serviços Administrativos", codigo: "7721700", descricao: "Aluguel de equipamentos recreativos e esportivos" },
  { secao: "Serviços Administrativos", codigo: "7722500", descricao: "Aluguel de fitas de vídeo, DVDs e similares" },
  { secao: "Serviços Administrativos", codigo: "7723300", descricao: "Aluguel de objetos do vestuário, jóias e acessórios" },
  { secao: "Serviços Administrativos", codigo: "7729202", descricao: "Aluguel de aparelhos de jogos eletrônicos" },
  { secao: "Serviços Administrativos", codigo: "7810800", descricao: "Seleção e agenciamento de mão-de-obra" },
  { secao: "Serviços Administrativos", codigo: "7820500", descricao: "Locação de mão-de-obra temporária" },
  { secao: "Serviços Administrativos", codigo: "7830200", descricao: "Fornecimento e gestão de recursos humanos para terceiros" },
  { secao: "Serviços Administrativos", codigo: "7911200", descricao: "Agências de viagens" },
  { secao: "Serviços Administrativos", codigo: "7912100", descricao: "Operadores turísticos" },
  { secao: "Serviços Administrativos", codigo: "7990200", descricao: "Serviços de reservas e outros serviços de turismo" },
  { secao: "Serviços Administrativos", codigo: "8011101", descricao: "Atividades de vigilância e segurança privada" },
  { secao: "Serviços Administrativos", codigo: "8011102", descricao: "Serviços de adestramento de cães de guarda" },
  { secao: "Serviços Administrativos", codigo: "8012900", descricao: "Atividades de transporte de valores" },
  { secao: "Serviços Administrativos", codigo: "8020000", descricao: "Atividades de monitoramento de sistemas de segurança eletrônica" },
  { secao: "Serviços Administrativos", codigo: "8111700", descricao: "Serviços combinados para apoio a edifícios" },
  { secao: "Serviços Administrativos", codigo: "8112500", descricao: "Condomínios prediais" },
  { secao: "Serviços Administrativos", codigo: "8121400", descricao: "Limpeza em prédios e em domicílios" },
  { secao: "Serviços Administrativos", codigo: "8122200", descricao: "Imunização e controle de pragas urbanas" },
  { secao: "Serviços Administrativos", codigo: "8129000", descricao: "Atividades de limpeza não especificadas anteriormente" },
  { secao: "Serviços Administrativos", codigo: "8130300", descricao: "Atividades paisagísticas" },
  { secao: "Serviços Administrativos", codigo: "8211300", descricao: "Serviços combinados de escritório e apoio administrativo" },
  { secao: "Serviços Administrativos", codigo: "8219901", descricao: "Fotocópias" },
  { secao: "Serviços Administrativos", codigo: "8219999", descricao: "Serviços de apoio administrativo não especificados anteriormente" },
  { secao: "Serviços Administrativos", codigo: "8230001", descricao: "Serviços de organização de feiras, congressos, exposições e festas" },
  { secao: "Serviços Administrativos", codigo: "8230002", descricao: "Casas de festas e eventos" },
  { secao: "Serviços Administrativos", codigo: "8291100", descricao: "Atividades de cobranças e informações cadastrais" },
  { secao: "Serviços Administrativos", codigo: "8292000", descricao: "Envasamento e empacotamento sob contrato" },
  { secao: "Serviços Administrativos", codigo: "8299701", descricao: "Medição de consumo de energia elétrica, gás e água" },
  { secao: "Serviços Administrativos", codigo: "8299702", descricao: "Emissão de vales-alimentação, vales-transporte e similares" },
  { secao: "Serviços Administrativos", codigo: "8299703", descricao: "Serviços de gravação de carimbos" },
  { secao: "Serviços Administrativos", codigo: "8299704", descricao: "Leiloeiros independentes" },
  { secao: "Serviços Administrativos", codigo: "8299705", descricao: "Serviços de levantamento de fundos sob contrato" },

  // P - EDUCAÇÃO
  { secao: "Educação", codigo: "8511200", descricao: "Educação infantil - creche" },
  { secao: "Educação", codigo: "8512100", descricao: "Educação infantil - pré-escola" },
  { secao: "Educação", codigo: "8513900", descricao: "Ensino fundamental" },
  { secao: "Educação", codigo: "8520100", descricao: "Ensino médio" },
  { secao: "Educação", codigo: "8531700", descricao: "Educação superior - graduação" },
  { secao: "Educação", codigo: "8532500", descricao: "Educação superior - graduação e pós-graduação" },
  { secao: "Educação", codigo: "8533300", descricao: "Educação superior - pós-graduação e extensão" },
  { secao: "Educação", codigo: "8541400", descricao: "Educação profissional de nível técnico" },
  { secao: "Educação", codigo: "8542200", descricao: "Educação profissional de nível tecnológico" },
  { secao: "Educação", codigo: "8550301", descricao: "Administração de caixas escolares" },
  { secao: "Educação", codigo: "8550302", descricao: "Atividades de apoio à educação" },
  { secao: "Educação", codigo: "8591100", descricao: "Ensino de esportes" },
  { secao: "Educação", codigo: "8592901", descricao: "Ensino de dança" },
  { secao: "Educação", codigo: "8592902", descricao: "Ensino de artes cênicas" },
  { secao: "Educação", codigo: "8592903", descricao: "Ensino de música" },
  { secao: "Educação", codigo: "8593700", descricao: "Ensino de idiomas" },
  { secao: "Educação", codigo: "8599601", descricao: "Formação de condutores" },
  { secao: "Educação", codigo: "8599602", descricao: "Cursos de pilotagem" },
  { secao: "Educação", codigo: "8599603", descricao: "Treinamento em informática" },
  { secao: "Educação", codigo: "8599604", descricao: "Treinamento em desenvolvimento profissional e gerencial" },
  { secao: "Educação", codigo: "8599605", descricao: "Cursos preparatórios para concursos" },

  // Q - SAÚDE
  { secao: "Saúde", codigo: "8610101", descricao: "Atividades de atendimento hospitalar" },
  { secao: "Saúde", codigo: "8610102", descricao: "UTI móvel" },
  { secao: "Saúde", codigo: "8621601", descricao: "UPA e congêneres" },
  { secao: "Saúde", codigo: "8621602", descricao: "Serviços móveis de atendimento a urgências" },
  { secao: "Saúde", codigo: "8622400", descricao: "Serviços de remoção de pacientes" },
  { secao: "Saúde", codigo: "8630501", descricao: "Atividade médica ambulatorial com recursos para realização de procedimentos cirúrgicos" },
  { secao: "Saúde", codigo: "8630502", descricao: "Atividade médica ambulatorial com recursos para realização de exames complementares" },
  { secao: "Saúde", codigo: "8630503", descricao: "Atividade médica ambulatorial restrita a consultas" },
  { secao: "Saúde", codigo: "8630504", descricao: "Atividade odontológica" },
  { secao: "Saúde", codigo: "8630506", descricao: "Serviços de vacinação e imunização humana" },
  { secao: "Saúde", codigo: "8630507", descricao: "Atividades de reprodução humana assistida" },
  { secao: "Saúde", codigo: "8640201", descricao: "Laboratórios de anatomia patológica e citológica" },
  { secao: "Saúde", codigo: "8640202", descricao: "Laboratórios clínicos" },
  { secao: "Saúde", codigo: "8640203", descricao: "Serviços de diálise e nefrologia" },
  { secao: "Saúde", codigo: "8640204", descricao: "Serviços de tomografia" },
  { secao: "Saúde", codigo: "8640205", descricao: "Serviços de diagnóstico por imagem com uso de radiação ionizante" },
  { secao: "Saúde", codigo: "8640206", descricao: "Serviços de ressonância magnética" },
  { secao: "Saúde", codigo: "8640207", descricao: "Serviços de diagnóstico por imagem sem uso de radiação ionizante" },
  { secao: "Saúde", codigo: "8640208", descricao: "Serviços de diagnóstico por registro gráfico" },
  { secao: "Saúde", codigo: "8640209", descricao: "Serviços de diagnóstico por métodos ópticos" },
  { secao: "Saúde", codigo: "8640210", descricao: "Serviços de quimioterapia" },
  { secao: "Saúde", codigo: "8640211", descricao: "Serviços de radioterapia" },
  { secao: "Saúde", codigo: "8640212", descricao: "Serviços de hemoterapia" },
  { secao: "Saúde", codigo: "8640213", descricao: "Serviços de litotripsia" },
  { secao: "Saúde", codigo: "8640214", descricao: "Serviços de bancos de células e tecidos humanos" },
  { secao: "Saúde", codigo: "8650001", descricao: "Atividades de enfermagem" },
  { secao: "Saúde", codigo: "8650002", descricao: "Atividades de profissionais da nutrição" },
  { secao: "Saúde", codigo: "8650003", descricao: "Atividades de psicologia e psicanálise" },
  { secao: "Saúde", codigo: "8650004", descricao: "Atividades de fisioterapia" },
  { secao: "Saúde", codigo: "8650005", descricao: "Atividades de terapia ocupacional" },
  { secao: "Saúde", codigo: "8650006", descricao: "Atividades de fonoaudiologia" },
  { secao: "Saúde", codigo: "8650007", descricao: "Atividades de terapia de nutrição enteral e parenteral" },
  { secao: "Saúde", codigo: "8660700", descricao: "Atividades de apoio à gestão de saúde" },
  { secao: "Saúde", codigo: "8690901", descricao: "Atividades de práticas integrativas e complementares em saúde humana" },
  { secao: "Saúde", codigo: "8690903", descricao: "Atividades de acupuntura" },
  { secao: "Saúde", codigo: "8711501", descricao: "Clínicas e residências geriátricas" },
  { secao: "Saúde", codigo: "8720401", descricao: "Atividades de centros de assistência psicossocial" },
  { secao: "Saúde", codigo: "8730101", descricao: "Orfanatos" },

  // R - ARTES E ENTRETENIMENTO
  { secao: "Arte e Entretenimento", codigo: "9001901", descricao: "Produção teatral" },
  { secao: "Arte e Entretenimento", codigo: "9001902", descricao: "Produção musical" },
  { secao: "Arte e Entretenimento", codigo: "9001903", descricao: "Produção de espetáculos de dança" },
  { secao: "Arte e Entretenimento", codigo: "9001904", descricao: "Produção de espetáculos circenses, de marionetes e similares" },
  { secao: "Arte e Entretenimento", codigo: "9001905", descricao: "Produção de espetáculos de rodeios, vaquejadas e similares" },
  { secao: "Arte e Entretenimento", codigo: "9001906", descricao: "Atividades de sonorização e de iluminação" },
  { secao: "Arte e Entretenimento", codigo: "9002701", descricao: "Atividades de artistas plásticos" },
  { secao: "Arte e Entretenimento", codigo: "9003500", descricao: "Gestão de espaços para artes cênicas, espetáculos e outras atividades artísticas" },
  { secao: "Arte e Entretenimento", codigo: "9101500", descricao: "Atividades de bibliotecas e arquivos" },
  { secao: "Arte e Entretenimento", codigo: "9102301", descricao: "Atividades de museus e de exploração, restauração artística e conservação de lugares e prédios históricos" },
  { secao: "Arte e Entretenimento", codigo: "9200301", descricao: "Casas de bingo" },
  { secao: "Arte e Entretenimento", codigo: "9200302", descricao: "Exploração de apostas em corridas de cavalos" },
  { secao: "Arte e Entretenimento", codigo: "9200399", descricao: "Exploração de jogos de azar e apostas não especificados anteriormente" },
  { secao: "Arte e Entretenimento", codigo: "9311500", descricao: "Gestão de instalações de esportes" },
  { secao: "Arte e Entretenimento", codigo: "9312300", descricao: "Clubes sociais, esportivos e similares" },
  { secao: "Arte e Entretenimento", codigo: "9313100", descricao: "Atividades de condicionamento físico" },
  { secao: "Arte e Entretenimento", codigo: "9319101", descricao: "Produção e promoção de eventos esportivos" },
  { secao: "Arte e Entretenimento", codigo: "9321200", descricao: "Parques de diversão e parques temáticos" },
  { secao: "Arte e Entretenimento", codigo: "9329801", descricao: "Discotecas, danceterias, salões de dança e similares" },
  { secao: "Arte e Entretenimento", codigo: "9329802", descricao: "Jogos eletrônicos" },
  { secao: "Arte e Entretenimento", codigo: "9329803", descricao: "Serviços de tatuagem e colocação de piercing" },
  { secao: "Arte e Entretenimento", codigo: "9329804", descricao: "Exploração de boliches" },
  { secao: "Arte e Entretenimento", codigo: "9329899", descricao: "Outras atividades de recreação e lazer não especificadas anteriormente" },

  // S - OUTROS SERVIÇOS
  { secao: "Outros Serviços", codigo: "9411100", descricao: "Atividades de organizações associativas patronais e empresariais" },
  { secao: "Outros Serviços", codigo: "9412001", descricao: "Atividades de fiscalização profissional" },
  { secao: "Outros Serviços", codigo: "9420100", descricao: "Atividades de organizações sindicais" },
  { secao: "Outros Serviços", codigo: "9430800", descricao: "Atividades de associações de defesa de direitos sociais" },
  { secao: "Outros Serviços", codigo: "9491000", descricao: "Atividades de organizações religiosas ou filosóficas" },
  { secao: "Outros Serviços", codigo: "9492800", descricao: "Atividades de organizações políticas" },
  { secao: "Outros Serviços", codigo: "9493600", descricao: "Atividades de organizações associativas ligadas à cultura e à arte" },
  { secao: "Outros Serviços", codigo: "9601701", descricao: "Lavanderias" },
  { secao: "Outros Serviços", codigo: "9601702", descricao: "Tinturarias" },
  { secao: "Outros Serviços", codigo: "9601703", descricao: "Toalheiros" },
  { secao: "Outros Serviços", codigo: "9602501", descricao: "Cabeleireiros, manicure e pedicure" },
  { secao: "Outros Serviços", codigo: "9602502", descricao: "Atividades de estética e outros serviços de cuidados com a beleza" },
  { secao: "Outros Serviços", codigo: "9603301", descricao: "Gestão e manutenção de cemitérios" },
  { secao: "Outros Serviços", codigo: "9603302", descricao: "Serviços de cremação" },
  { secao: "Outros Serviços", codigo: "9603303", descricao: "Serviços de sepultamento" },
  { secao: "Outros Serviços", codigo: "9603304", descricao: "Serviços de funerárias" },
  { secao: "Outros Serviços", codigo: "9609202", descricao: "Agências matrimoniais" },
  { secao: "Outros Serviços", codigo: "9609204", descricao: "Exploração de máquinas de serviços pessoais acionadas por moeda" },
  { secao: "Outros Serviços", codigo: "9609205", descricao: "Atividades de sauna e banhos" },
  { secao: "Outros Serviços", codigo: "9609206", descricao: "Serviços de maquiagem artística" },
  { secao: "Outros Serviços", codigo: "9609207", descricao: "Alojamento de animais domésticos" },
  { secao: "Outros Serviços", codigo: "9609208", descricao: "Higiene e embelezamento de animais domésticos" },
  { secao: "Outros Serviços", codigo: "9609299", descricao: "Outras atividades de serviços pessoais não especificadas anteriormente" },

  // Reparação
  { secao: "Reparação e Manutenção", codigo: "9511800", descricao: "Reparação e manutenção de computadores e de equipamentos periféricos" },
  { secao: "Reparação e Manutenção", codigo: "9512600", descricao: "Reparação e manutenção de equipamentos de comunicação" },
  { secao: "Reparação e Manutenção", codigo: "9521500", descricao: "Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico" },
  { secao: "Reparação e Manutenção", codigo: "9529101", descricao: "Reparação de calçados, bolsas e artigos de viagem" },
  { secao: "Reparação e Manutenção", codigo: "9529102", descricao: "Chaveiros" },
  { secao: "Reparação e Manutenção", codigo: "9529103", descricao: "Reparação de relógios" },
  { secao: "Reparação e Manutenção", codigo: "9529104", descricao: "Reparação de bicicletas, triciclos e outros veículos não-motorizados" },
  { secao: "Reparação e Manutenção", codigo: "9529105", descricao: "Reparação de artigos do mobiliário" },
]

export function searchCnaes(query: string): Cnae[] {
  if (!query || query.length < 2) return []
  const q = query.toLowerCase()
  return CNAES.filter(
    (c) => c.codigo.includes(q) || c.descricao.toLowerCase().includes(q) || c.secao.toLowerCase().includes(q),
  ).slice(0, 50)
}
